timezone: Europe/Paris
docker_user: hl_docker

ssh_public_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIISmH5fdHgqol2WI4f7xWKbQXmhT14gnSWuMEfhndhcR" # Laptop
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJviVET/PFXmn6gjkAc1IAwcrePqlUF8JWSWW4P+aHCn" # Main
