---
homelab_networks_dns_servers:
  - 1.1.1.1
  - 1.0.0.1
homelab_networks_blocked_ipv4:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - 100.64.0.0/10
homelab_networks_blocked_ipv6:
  - fc00::/7
  - fe80::/10
homelab_networks_script: /usr/local/sbin/homelab-container-firewall
