---
- name: Disable unused services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ system_services_unused_services }}"
  register: system_services_unused_services_result
  failed_when: >-
    system_services_unused_services_result is failed and
    "Could not find the requested service" not in (system_services_unused_services_result.msg | default(""))
