---
fail2ban_packages:
  - fail2ban
  - python3-systemd
  - whois
fail2ban_ignore_ips:
  - 127.0.0.1/32
  - 192.168.0.0/16
fail2ban_bantime: 1h
fail2ban_findtime: 10m
fail2ban_maxretry: 5
fail2ban_backend: systemd
fail2ban_alert_email: root@localhost
fail2ban_sender: "fail2ban@{{ ansible_fqdn | default(inventory_hostname) }}"
fail2ban_mta: sendmail
fail2ban_action: "%(action_mwl)s"
fail2ban_sshd_enabled: true
fail2ban_sshd_port: "{{ ssh_port | default(23145) }}"
fail2ban_sshd_logpath: "%(sshd_log)s"
